name: Dependency Management
run-name: Manages direct project dependencies
on: [pull_request]
jobs:
  Version-Sync:
    name: Run syncpack to find version mismatches
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm i -g pnpm@8.6.12

      - name: Install npm dependencies
        run: pnpm i

      - name: Run Syncpack
        run: pnpm find-version-mismatch:ci